# Generated by Django 5.1.15 on 2026-06-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_slot_fk_not_o2o'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='scheduling__patient_2517a4_idx',
            old_name='scheduling_patient_44d7d5_idx',
        ),
        migrations.RenameIndex(
            model_name='slot',
            new_name='scheduling__doctor__5915e9_idx',
            old_name='scheduling_doctor__1b7498_idx',
        ),
    ]
